# Generated by Django 4.0.1 on 2022-01-16 16:25

from django.db import migrations, models
import todo_manager_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=todo_manager_app.models.user_directory_path),
        ),
    ]
