# Generated by Django 4.0.1 on 2022-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_manager_app', '0002_alter_todo_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
