# Generated by Django 4.0.1 on 2022-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_manager_app', '0003_alter_todo_status_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status_done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
